//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIElementRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIElement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIElement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RapidDoc.Resources.UIElement.UIElement", typeof(UIElement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить комментарий.
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить файлы....
        /// </summary>
        public static string AddFiles {
            get {
                return ResourceManager.GetString("AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлен новый документ.
        /// </summary>
        public static string AddingNewDocEmail {
            get {
                return ResourceManager.GetString("AddingNewDocEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительные.
        /// </summary>
        public static string Additional {
            get {
                return ResourceManager.GetString("Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительные установки.
        /// </summary>
        public static string AddonSettings {
            get {
                return ResourceManager.GetString("AddonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить роли.
        /// </summary>
        public static string AddRoles {
            get {
                return ResourceManager.GetString("AddRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить пользователей.
        /// </summary>
        public static string AddUsers {
            get {
                return ResourceManager.GetString("AddUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Согласованные.
        /// </summary>
        public static string AgreedDocument {
            get {
                return ResourceManager.GetString("AgreedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Утвердить.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Согласовали документ:.
        /// </summary>
        public static string ApproveDocument {
            get {
                return ResourceManager.GetString("ApproveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прикрепленные файлы.
        /// </summary>
        public static string AttachedFiles {
            get {
                return ResourceManager.GetString("AttachedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основные.
        /// </summary>
        public static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Календарь.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение пароля.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы зашли под.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать компанию.
        /// </summary>
        public static string ChooseCompany {
            get {
                return ResourceManager.GetString("ChooseCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компании.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите отклонить документ?.
        /// </summary>
        public static string ConfirmationReject {
            get {
                return ResourceManager.GetString("ConfirmationReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копию.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скопирован документ.
        /// </summary>
        public static string CopyDocumentHistory {
            get {
                return ResourceManager.GetString("CopyDocumentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая учетная запись.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая компания.
        /// </summary>
        public static string CreateCompany {
            get {
                return ResourceManager.GetString("CreateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить делегирование.
        /// </summary>
        public static string CreateDelegation {
            get {
                return ResourceManager.GetString("CreateDelegation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое подразделение.
        /// </summary>
        public static string CreateDepartment {
            get {
                return ResourceManager.GetString("CreateDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый домен.
        /// </summary>
        public static string CreateDomain {
            get {
                return ResourceManager.GetString("CreateDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый сотрудник.
        /// </summary>
        public static string CreateEmpl {
            get {
                return ResourceManager.GetString("CreateEmpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая группа процессов.
        /// </summary>
        public static string CreateGroupProcess {
            get {
                return ResourceManager.GetString("CreateGroupProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая номерная серия.
        /// </summary>
        public static string CreateNumberSeq {
            get {
                return ResourceManager.GetString("CreateNumberSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый процесс.
        /// </summary>
        public static string CreateProcess {
            get {
                return ResourceManager.GetString("CreateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый профиль.
        /// </summary>
        public static string CreateProfile {
            get {
                return ResourceManager.GetString("CreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формирование отчета.
        /// </summary>
        public static string CreateReport {
            get {
                return ResourceManager.GetString("CreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая роль.
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый сервис инцидента.
        /// </summary>
        public static string CreateServiceIncident {
            get {
                return ResourceManager.GetString("CreateServiceIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать задачу.
        /// </summary>
        public static string CreateTask {
            get {
                return ResourceManager.GetString("CreateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая должность.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пользователь.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый график работ.
        /// </summary>
        public static string CreateWorkSchedule {
            get {
                return ResourceManager.GetString("CreateWorkSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рабочее время должно быть по UTC, без учета часовых поясов.
        /// </summary>
        public static string CreateWorkTimeHint {
            get {
                return ResourceManager.GetString("CreateWorkTimeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рабочая область.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Делегировать.
        /// </summary>
        public static string Delegate {
            get {
                return ResourceManager.GetString("Delegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Делегирована задача.
        /// </summary>
        public static string DelegateTaskHistory {
            get {
                return ResourceManager.GetString("DelegateTaskHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Делегирование.
        /// </summary>
        public static string Delegations {
            get {
                return ResourceManager.GetString("Delegations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подразделения.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробности.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детальный отчет.
        /// </summary>
        public static string DetailReport {
            get {
                return ResourceManager.GetString("DetailReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группы рассылки.
        /// </summary>
        public static string DistributionGroup {
            get {
                return ResourceManager.GetString("DistributionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавили читателей:.
        /// </summary>
        public static string DocumentAddReaders {
            get {
                return ResourceManager.GetString("DocumentAddReaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив.
        /// </summary>
        public static string DocumentArchive {
            get {
                return ResourceManager.GetString("DocumentArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл удален.
        /// </summary>
        public static string DocumentDeletedFile {
            get {
                return ResourceManager.GetString("DocumentDeletedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ отменен:.
        /// </summary>
        public static string DocumentReject {
            get {
                return ResourceManager.GetString("DocumentReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалили читателей: .
        /// </summary>
        public static string DocumentRemoveReaders {
            get {
                return ResourceManager.GetString("DocumentRemoveReaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домены.
        /// </summary>
        public static string Domains {
            get {
                return ResourceManager.GetString("Domains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры почты.
        /// </summary>
        public static string EmailParameter {
            get {
                return ResourceManager.GetString("EmailParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнителя.
        /// </summary>
        public static string Executor {
            get {
                return ResourceManager.GetString("Executor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Из архива.
        /// </summary>
        public static string FromArchive {
            get {
                return ResourceManager.GetString("FromArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группы процессов.
        /// </summary>
        public static string GroupProcesses {
            get {
                return ResourceManager.GetString("GroupProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификация.
        /// </summary>
        public static string Identification {
            get {
                return ResourceManager.GetString("Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициатор.
        /// </summary>
        public static string Initiator {
            get {
                return ResourceManager.GetString("Initiator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru-RU.
        /// </summary>
        public static string LangFullName {
            get {
                return ResourceManager.GetString("LangFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru.
        /// </summary>
        public static string LangName {
            get {
                return ResourceManager.GetString("LangName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на документ.
        /// </summary>
        public static string LinkToDocument {
            get {
                return ResourceManager.GetString("LinkToDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для копирования ссылки нажмите Ctrl+C.
        /// </summary>
        public static string LinkToDocumentText {
            get {
                return ResourceManager.GetString("LinkToDocumentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to если у вас ещё нет учетной записи.
        /// </summary>
        public static string LogInNoAccount {
            get {
                return ResourceManager.GetString("LogInNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Используя вашу учетную запись.
        /// </summary>
        public static string LogInTitle {
            get {
                return ResourceManager.GetString("LogInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки пользователя.
        /// </summary>
        public static string ManageAccount {
            get {
                return ResourceManager.GetString("ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проработан документ.
        /// </summary>
        public static string ModifiedDocumentHistory {
            get {
                return ResourceManager.GetString("ModifiedDocumentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мониторинг.
        /// </summary>
        public static string Monitoring {
            get {
                return ResourceManager.GetString("Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В документе нужно прикрепить {0} файл(-ов).
        /// </summary>
        public static string MustAttachedFiles {
            get {
                return ResourceManager.GetString("MustAttachedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои документы.
        /// </summary>
        public static string MyDocument {
            get {
                return ResourceManager.GetString("MyDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активные документы.
        /// </summary>
        public static string MyProcesses {
            get {
                return ResourceManager.GetString("MyProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавили новый комментарий:.
        /// </summary>
        public static string NewComment {
            get {
                return ResourceManager.GetString("NewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создали новый документ:.
        /// </summary>
        public static string NewDocument {
            get {
                return ResourceManager.GetString("NewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас отсутствует доступ на просмотр этого документа.
        /// </summary>
        public static string NoAccess {
            get {
                return ResourceManager.GetString("NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствуют.
        /// </summary>
        public static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас отключен JavaScript. Сайт может отображаться некорректно. Рекомендуем включить JavaScript..
        /// </summary>
        public static string NoJS {
            get {
                return ResourceManager.GetString("NoJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбрано.
        /// </summary>
        public static string NoValue {
            get {
                return ResourceManager.GetString("NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номерные серии.
        /// </summary>
        public static string NumberSeqs {
            get {
                return ResourceManager.GetString("NumberSeqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На доработку.
        /// </summary>
        public static string OnRework {
            get {
                return ResourceManager.GetString("OnRework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница не найдена.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попробуйте проверить правильность указаного адреса или перейдите на главную страницу.
        /// </summary>
        public static string PageNotFoundText {
            get {
                return ResourceManager.GetString("PageNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Страница не найдена.
        /// </summary>
        public static string PageNotFoundTitle {
            get {
                return ResourceManager.GetString("PageNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановление пароля.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнение.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнение по подразделениям.
        /// </summary>
        public static string PerformanceDepartment {
            get {
                return ResourceManager.GetString("PerformanceDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процессы.
        /// </summary>
        public static string Processes {
            get {
                return ResourceManager.GetString("Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профили.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система управления процессами компании.
        /// </summary>
        public static string ProgramDescription {
            get {
                return ResourceManager.GetString("ProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ход работы.
        /// </summary>
        public static string ProgressWork {
            get {
                return ResourceManager.GetString("ProgressWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продление срока.
        /// </summary>
        public static string Prolong {
            get {
                return ResourceManager.GetString("Prolong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читателя.
        /// </summary>
        public static string Reader {
            get {
                return ResourceManager.GetString("Reader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справочники.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отклонить.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменили документ:.
        /// </summary>
        public static string RejectDocument {
            get {
                return ResourceManager.GetString("RejectDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При отклонении документа, нужно обязательно указать причину отклонения в комментарии к документу.
        /// </summary>
        public static string RejectReason {
            get {
                return ResourceManager.GetString("RejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связанные документы.
        /// </summary>
        public static string RelatedTasks {
            get {
                return ResourceManager.GetString("RelatedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заменить.
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по маршрутам.
        /// </summary>
        public static string ReportOfRoutes {
            get {
                return ResourceManager.GetString("ReportOfRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчеты.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить пароль.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сформировать.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить черновик.
        /// </summary>
        public static string SaveDraft {
            get {
                return ResourceManager.GetString("SaveDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено результатов: .
        /// </summary>
        public static string SearchResultText {
            get {
                return ResourceManager.GetString("SearchResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст поиска, более 3 символов.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маршрут.
        /// </summary>
        public static string SendBookmark {
            get {
                return ResourceManager.GetString("SendBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На вас настроенно делегирование с пользователя.
        /// </summary>
        public static string SendDelegationEmplEmail {
            get {
                return ResourceManager.GetString("SendDelegationEmplEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вам назначен документ.
        /// </summary>
        public static string SendExecutorEmail {
            get {
                return ResourceManager.GetString("SendExecutorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ закрыт.
        /// </summary>
        public static string SendInitiatorClosedEmail {
            get {
                return ResourceManager.GetString("SendInitiatorClosedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый комментарий в документе.
        /// </summary>
        public static string SendInitiatorCommentEmail {
            get {
                return ResourceManager.GetString("SendInitiatorCommentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы создали новый документ.
        /// </summary>
        public static string SendInitiatorEmail {
            get {
                return ResourceManager.GetString("SendInitiatorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш документ был отменен.
        /// </summary>
        public static string SendInitiatorRejectEmail {
            get {
                return ResourceManager.GetString("SendInitiatorRejectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ на доработку.
        /// </summary>
        public static string SendModificationUserEmail {
            get {
                return ResourceManager.GetString("SendModificationUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вас добавили читателем к документу.
        /// </summary>
        public static string SendReaderEmail {
            get {
                return ResourceManager.GetString("SendReaderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнение по документу просрочено.
        /// </summary>
        public static string SendSLADisturbanceEmail {
            get {
                return ResourceManager.GetString("SendSLADisturbanceEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Срок исполнения по документу подходит подходит к концу.
        /// </summary>
        public static string SendSLAWarningEmail {
            get {
                return ResourceManager.GetString("SendSLAWarningEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервисы инцидентов.
        /// </summary>
        public static string ServiceIncident {
            get {
                return ResourceManager.GetString("ServiceIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string SignInLogin {
            get {
                return ResourceManager.GetString("SignInLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, войдите.
        /// </summary>
        public static string SignInPlease {
            get {
                return ResourceManager.GetString("SignInPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сотрудники.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддерживаемые типы файлов.
        /// </summary>
        public static string SupportFileTypes {
            get {
                return ResourceManager.GetString("SupportFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблоны.
        /// </summary>
        public static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Должности.
        /// </summary>
        public static string Titles {
            get {
                return ResourceManager.GetString("Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В архив.
        /// </summary>
        public static string ToArchive {
            get {
                return ResourceManager.GetString("ToArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление о прочтении документа при следовании по маршруту согласования.
        /// </summary>
        public static string TooltipAboutReading {
            get {
                return ResourceManager.GetString("TooltipAboutReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТОП.
        /// </summary>
        public static string TOP {
            get {
                return ResourceManager.GetString("TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать Windows авторизацию.
        /// </summary>
        public static string UseWindowsAuthentication {
            get {
                return ResourceManager.GetString("UseWindowsAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидает.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отозвать.
        /// </summary>
        public static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отозван документ.
        /// </summary>
        public static string WithdrawHistory {
            get {
                return ResourceManager.GetString("WithdrawHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ отозван инициатором.
        /// </summary>
        public static string Withdrawn {
            get {
                return ResourceManager.GetString("Withdrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отозвать документ?.
        /// </summary>
        public static string WithdrawQuestion {
            get {
                return ResourceManager.GetString("WithdrawQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to График работ.
        /// </summary>
        public static string WorkSchedule {
            get {
                return ResourceManager.GetString("WorkSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Графики работ.
        /// </summary>
        public static string WorkSchedules {
            get {
                return ResourceManager.GetString("WorkSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить?.
        /// </summary>
        public static string СonfirmDeletion {
            get {
                return ResourceManager.GetString("СonfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите сбросить пароль?.
        /// </summary>
        public static string СonfirmResetPassword {
            get {
                return ResourceManager.GetString("СonfirmResetPassword", resourceCulture);
            }
        }
    }
}
